#ifndef __CONTROL_H__
#define __CONTROL_H__


typedef enum
{
    CONTROL_PARAM_AMPLITUDE,
    CONTROL_PARAM_MODWHEEL,
    CONTROL_PARAM_PANNING,
    CONTROL_PARAM_CUTOFF,
    CONTROL_PARAM_RESONANCE,
    CONTROL_PARAM_PITCH,
    CONTROL_PARAM_PORTAMENTO,
    CONTROL_PARAM_PORTAMENTO_TIME,
    CONTROL_PARAM_CUTOFF_MOD1_AMT,
    CONTROL_PARAM_RESO_MOD1_AMT

} ControlParamType;


#endif /* __CONTROL_H__ */
